[2025-07-12T13:43:02.367+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flight_data_etl.transform_flight_data manual__2025-07-12T13:42:58.540156+00:00 [queued]>
[2025-07-12T13:43:02.370+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flight_data_etl.transform_flight_data manual__2025-07-12T13:42:58.540156+00:00 [queued]>
[2025-07-12T13:43:02.370+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-07-12T13:43:02.375+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform_flight_data> on 2025-07-12 13:42:58.540156+00:00
[2025-07-12T13:43:02.377+0000] {standard_task_runner.py:60} INFO - Started process 295 to run task
[2025-07-12T13:43:02.379+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'flight_data_etl', 'transform_flight_data', 'manual__2025-07-12T13:42:58.540156+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/flight_data_etl.py', '--cfg-path', '/tmp/tmpk4nls4qe']
[2025-07-12T13:43:02.380+0000] {standard_task_runner.py:88} INFO - Job 8: Subtask transform_flight_data
[2025-07-12T13:43:02.397+0000] {task_command.py:423} INFO - Running <TaskInstance: flight_data_etl.transform_flight_data manual__2025-07-12T13:42:58.540156+00:00 [running]> on host d712b9c489aa
[2025-07-12T13:43:02.496+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_engineer' AIRFLOW_CTX_DAG_ID='flight_data_etl' AIRFLOW_CTX_TASK_ID='transform_flight_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-12T13:42:58.540156+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-12T13:42:58.540156+00:00'
[2025-07-12T13:43:02.511+0000] {logging_mixin.py:188} INFO - Error transforming data: Error tokenizing data. C error: Expected 10 fields in line 93, saw 19
[2025-07-12T13:43:02.512+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/flight_data_etl.py", line 163, in transform_flight_data
    schedule_data = pd.read_csv('/opt/airflow/data/flight_schedule_data.csv')
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 583, in _read
    return parser.read(nrows)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1704, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 875, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 850, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 861, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "pandas/_libs/parsers.pyx", line 2029, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 10 fields in line 93, saw 19

[2025-07-12T13:43:02.515+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=flight_data_etl, task_id=transform_flight_data, execution_date=20250712T134258, start_date=20250712T134302, end_date=20250712T134302
[2025-07-12T13:43:02.519+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 8 for task transform_flight_data (Error tokenizing data. C error: Expected 10 fields in line 93, saw 19
; 295)
[2025-07-12T13:43:02.523+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-12T13:43:02.532+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
