[2025-07-12T15:07:32.756+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flight_analytics_dag.analyze_flight_patterns scheduled__2025-07-12T00:00:00+00:00 [queued]>
[2025-07-12T15:07:32.759+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flight_analytics_dag.analyze_flight_patterns scheduled__2025-07-12T00:00:00+00:00 [queued]>
[2025-07-12T15:07:32.759+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-07-12T15:07:32.763+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): analyze_flight_patterns> on 2025-07-12 00:00:00+00:00
[2025-07-12T15:07:32.765+0000] {standard_task_runner.py:60} INFO - Started process 446 to run task
[2025-07-12T15:07:32.766+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'flight_analytics_dag', 'analyze_flight_patterns', 'scheduled__2025-07-12T00:00:00+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/flight_analytics_dag.py', '--cfg-path', '/tmp/tmpjct7fqxa']
[2025-07-12T15:07:32.767+0000] {standard_task_runner.py:88} INFO - Job 64: Subtask analyze_flight_patterns
[2025-07-12T15:07:32.783+0000] {task_command.py:423} INFO - Running <TaskInstance: flight_analytics_dag.analyze_flight_patterns scheduled__2025-07-12T00:00:00+00:00 [running]> on host b33104088b45
[2025-07-12T15:07:32.875+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_engineer' AIRFLOW_CTX_DAG_ID='flight_analytics_dag' AIRFLOW_CTX_TASK_ID='analyze_flight_patterns' AIRFLOW_CTX_EXECUTION_DATE='2025-07-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-12T00:00:00+00:00'
[2025-07-12T15:07:32.877+0000] {base.py:83} INFO - Using connection ID 'postgres_default' for task execution.
[2025-07-12T15:07:32.881+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:221 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-07-12T15:07:32.882+0000] {logging_mixin.py:188} INFO - ‚ùå Error in flight patterns analysis: Execution failed on sql '
        SELECT 
            EXTRACT(HOUR FROM scheduled_departure) as departure_hour,
            COUNT(*) as flight_count,
            AVG(flight_duration_minutes) as avg_duration,
            COUNT(DISTINCT airline) as airlines_operating
        FROM scheduled_flights 
        GROUP BY EXTRACT(HOUR FROM scheduled_departure)
        ORDER BY departure_hour;
        ': function pg_catalog.date_part(unknown, text) does not exist
LINE 3:             EXTRACT(HOUR FROM scheduled_departure) as depart...
                    ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
[2025-07-12T15:07:32.882+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 2018, in execute
    cur.execute(*args, **kwargs)
psycopg2.errors.UndefinedFunction: function pg_catalog.date_part(unknown, text) does not exist
LINE 3:             EXTRACT(HOUR FROM scheduled_departure) as depart...
                    ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/flight_analytics_dag.py", line 139, in analyze_flight_patterns
    patterns_data = postgres_hook.get_pandas_df(patterns_query)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 221, in get_pandas_df
    return psql.read_sql(sql, con=conn, params=parameters, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 564, in read_sql
    return pandas_sql.read_query(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 2078, in read_query
    cursor = self.execute(*args)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 2030, in execute
    raise ex from exc
pandas.errors.DatabaseError: Execution failed on sql '
        SELECT 
            EXTRACT(HOUR FROM scheduled_departure) as departure_hour,
            COUNT(*) as flight_count,
            AVG(flight_duration_minutes) as avg_duration,
            COUNT(DISTINCT airline) as airlines_operating
        FROM scheduled_flights 
        GROUP BY EXTRACT(HOUR FROM scheduled_departure)
        ORDER BY departure_hour;
        ': function pg_catalog.date_part(unknown, text) does not exist
LINE 3:             EXTRACT(HOUR FROM scheduled_departure) as depart...
                    ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

[2025-07-12T15:07:32.885+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=flight_analytics_dag, task_id=analyze_flight_patterns, execution_date=20250712T000000, start_date=20250712T150732, end_date=20250712T150732
[2025-07-12T15:07:32.888+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 64 for task analyze_flight_patterns (Execution failed on sql '
        SELECT 
            EXTRACT(HOUR FROM scheduled_departure) as departure_hour,
            COUNT(*) as flight_count,
            AVG(flight_duration_minutes) as avg_duration,
            COUNT(DISTINCT airline) as airlines_operating
        FROM scheduled_flights 
        GROUP BY EXTRACT(HOUR FROM scheduled_departure)
        ORDER BY departure_hour;
        ': function pg_catalog.date_part(unknown, text) does not exist
LINE 3:             EXTRACT(HOUR FROM scheduled_departure) as depart...
                    ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
; 446)
[2025-07-12T15:07:32.917+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-12T15:07:32.925+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
