[2025-07-12T13:43:32.026+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flight_data_quality_check.check_data_completeness scheduled__2025-07-12T00:00:00+00:00 [queued]>
[2025-07-12T13:43:32.032+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flight_data_quality_check.check_data_completeness scheduled__2025-07-12T00:00:00+00:00 [queued]>
[2025-07-12T13:43:32.032+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-07-12T13:43:32.040+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): check_data_completeness> on 2025-07-12 00:00:00+00:00
[2025-07-12T13:43:32.047+0000] {standard_task_runner.py:60} INFO - Started process 319 to run task
[2025-07-12T13:43:32.048+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'flight_data_quality_check', 'check_data_completeness', 'scheduled__2025-07-12T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/flight_data_quality.py', '--cfg-path', '/tmp/tmp9x2i99gp']
[2025-07-12T13:43:32.050+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask check_data_completeness
[2025-07-12T13:43:32.071+0000] {task_command.py:423} INFO - Running <TaskInstance: flight_data_quality_check.check_data_completeness scheduled__2025-07-12T00:00:00+00:00 [running]> on host d712b9c489aa
[2025-07-12T13:43:32.256+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_engineer' AIRFLOW_CTX_DAG_ID='flight_data_quality_check' AIRFLOW_CTX_TASK_ID='check_data_completeness' AIRFLOW_CTX_EXECUTION_DATE='2025-07-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-12T00:00:00+00:00'
[2025-07-12T13:43:32.264+0000] {base.py:83} INFO - Using connection ID 'postgres_default' for task execution.
[2025-07-12T13:43:32.266+0000] {logging_mixin.py:188} INFO - Error checking data completeness: connection to server at "postgres" (172.20.0.2), port 5432 failed: FATAL:  password authentication failed for user "postgres"
[2025-07-12T13:43:32.266+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/flight_data_quality.py", line 76, in check_data_completeness
    airports_result = postgres_hook.get_first(airports_query)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 270, in get_first
    return self.run(sql=sql, parameters=parameters, handler=fetch_one_handler)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 391, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 158, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "postgres" (172.20.0.2), port 5432 failed: FATAL:  password authentication failed for user "postgres"

[2025-07-12T13:43:32.270+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=flight_data_quality_check, task_id=check_data_completeness, execution_date=20250712T000000, start_date=20250712T134332, end_date=20250712T134332
[2025-07-12T13:43:32.276+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 11 for task check_data_completeness (connection to server at "postgres" (172.20.0.2), port 5432 failed: FATAL:  password authentication failed for user "postgres"
; 319)
[2025-07-12T13:43:32.321+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-12T13:43:32.354+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-12T14:21:19.795+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flight_data_quality_check.check_data_completeness scheduled__2025-07-12T00:00:00+00:00 [queued]>
[2025-07-12T14:21:19.799+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flight_data_quality_check.check_data_completeness scheduled__2025-07-12T00:00:00+00:00 [queued]>
[2025-07-12T14:21:19.799+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-07-12T14:21:19.804+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): check_data_completeness> on 2025-07-12 00:00:00+00:00
[2025-07-12T14:21:19.806+0000] {standard_task_runner.py:60} INFO - Started process 330 to run task
[2025-07-12T14:21:19.808+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'flight_data_quality_check', 'check_data_completeness', 'scheduled__2025-07-12T00:00:00+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/flight_data_quality.py', '--cfg-path', '/tmp/tmpqjvebkx2']
[2025-07-12T14:21:19.809+0000] {standard_task_runner.py:88} INFO - Job 48: Subtask check_data_completeness
[2025-07-12T14:21:19.829+0000] {task_command.py:423} INFO - Running <TaskInstance: flight_data_quality_check.check_data_completeness scheduled__2025-07-12T00:00:00+00:00 [running]> on host b78d8dd28f9c
[2025-07-12T14:21:19.946+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_engineer' AIRFLOW_CTX_DAG_ID='flight_data_quality_check' AIRFLOW_CTX_TASK_ID='check_data_completeness' AIRFLOW_CTX_EXECUTION_DATE='2025-07-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-12T00:00:00+00:00'
[2025-07-12T14:21:19.950+0000] {base.py:83} INFO - Using connection ID 'postgres_default' for task execution.
[2025-07-12T14:21:19.952+0000] {sql.py:450} INFO - Running statement: 
        SELECT 
            COUNT(*) as total_records,
            COUNT(code) as code_count,
            COUNT(name) as name_count,
            COUNT(latitude) as lat_count,
            COUNT(longitude) as lon_count
        FROM airports
        , parameters: None
[2025-07-12T14:21:19.953+0000] {sql.py:459} INFO - Rows affected: 1
[2025-07-12T14:21:19.953+0000] {logging_mixin.py:188} INFO - Airports completeness check:
[2025-07-12T14:21:19.953+0000] {logging_mixin.py:188} INFO - Total records: 10
[2025-07-12T14:21:19.954+0000] {logging_mixin.py:188} INFO - Code completeness: 10/10 (100.0%)
[2025-07-12T14:21:19.954+0000] {logging_mixin.py:188} INFO - Name completeness: 10/10 (100.0%)
[2025-07-12T14:21:19.954+0000] {logging_mixin.py:188} INFO - Coordinates completeness: 10/10 (100.0%)
[2025-07-12T14:21:19.957+0000] {base.py:83} INFO - Using connection ID 'postgres_default' for task execution.
[2025-07-12T14:21:19.958+0000] {sql.py:450} INFO - Running statement: 
        SELECT 
            COUNT(*) as total_records,
            COUNT(flight_number) as flight_num_count,
            COUNT(origin_airport) as origin_count,
            COUNT(destination_airport) as dest_count,
            COUNT(scheduled_departure) as dept_count
        FROM scheduled_flights
        , parameters: None
[2025-07-12T14:21:19.959+0000] {sql.py:459} INFO - Rows affected: 1
[2025-07-12T14:21:19.959+0000] {logging_mixin.py:188} INFO - Scheduled flights completeness check:
[2025-07-12T14:21:19.960+0000] {logging_mixin.py:188} INFO - Total records: 1000
[2025-07-12T14:21:19.960+0000] {logging_mixin.py:188} INFO - Flight number completeness: 1000/1000 (100.0%)
[2025-07-12T14:21:19.960+0000] {logging_mixin.py:188} INFO - Origin completeness: 1000/1000 (100.0%)
[2025-07-12T14:21:19.960+0000] {logging_mixin.py:188} INFO - Destination completeness: 1000/1000 (100.0%)
[2025-07-12T14:21:19.961+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-07-12T14:21:19.964+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=flight_data_quality_check, task_id=check_data_completeness, execution_date=20250712T000000, start_date=20250712T142119, end_date=20250712T142119
[2025-07-12T14:21:19.988+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-07-12T14:21:19.997+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
