[2025-07-12T13:48:08.183+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flight_data_etl.load_to_database scheduled__2025-07-12T06:00:00+00:00 [queued]>
[2025-07-12T13:48:08.186+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flight_data_etl.load_to_database scheduled__2025-07-12T06:00:00+00:00 [queued]>
[2025-07-12T13:48:08.187+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-07-12T13:48:08.192+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_to_database> on 2025-07-12 06:00:00+00:00
[2025-07-12T13:48:08.194+0000] {standard_task_runner.py:60} INFO - Started process 463 to run task
[2025-07-12T13:48:08.195+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'flight_data_etl', 'load_to_database', 'scheduled__2025-07-12T06:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/flight_data_etl.py', '--cfg-path', '/tmp/tmps1n7rn9h']
[2025-07-12T13:48:08.196+0000] {standard_task_runner.py:88} INFO - Job 16: Subtask load_to_database
[2025-07-12T13:48:08.213+0000] {task_command.py:423} INFO - Running <TaskInstance: flight_data_etl.load_to_database scheduled__2025-07-12T06:00:00+00:00 [running]> on host d712b9c489aa
[2025-07-12T13:48:08.299+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_engineer' AIRFLOW_CTX_DAG_ID='flight_data_etl' AIRFLOW_CTX_TASK_ID='load_to_database' AIRFLOW_CTX_EXECUTION_DATE='2025-07-12T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-12T06:00:00+00:00'
[2025-07-12T13:48:08.303+0000] {base.py:83} INFO - Using connection ID 'postgres_default' for task execution.
[2025-07-12T13:48:08.306+0000] {logging_mixin.py:188} INFO - Error loading airport data: (psycopg2.OperationalError) connection to server at "postgres" (172.20.0.2), port 5432 failed: FATAL:  password authentication failed for user "postgres"

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-07-12T13:48:08.310+0000] {base.py:83} INFO - Using connection ID 'postgres_default' for task execution.
[2025-07-12T13:48:08.311+0000] {logging_mixin.py:188} INFO - Error loading schedule data: (psycopg2.OperationalError) connection to server at "postgres" (172.20.0.2), port 5432 failed: FATAL:  password authentication failed for user "postgres"

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-07-12T13:48:08.327+0000] {base.py:83} INFO - Using connection ID 'postgres_default' for task execution.
[2025-07-12T13:48:08.329+0000] {logging_mixin.py:188} INFO - Error loading real-time data: (psycopg2.OperationalError) connection to server at "postgres" (172.20.0.2), port 5432 failed: FATAL:  password authentication failed for user "postgres"

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-07-12T13:48:08.329+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-07-12T13:48:08.332+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=flight_data_etl, task_id=load_to_database, execution_date=20250712T060000, start_date=20250712T134808, end_date=20250712T134808
[2025-07-12T13:48:08.379+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-07-12T13:48:08.386+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-12T14:21:22.360+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flight_data_etl.load_to_database scheduled__2025-07-12T06:00:00+00:00 [queued]>
[2025-07-12T14:21:22.364+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flight_data_etl.load_to_database scheduled__2025-07-12T06:00:00+00:00 [queued]>
[2025-07-12T14:21:22.364+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-07-12T14:21:22.369+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_to_database> on 2025-07-12 06:00:00+00:00
[2025-07-12T14:21:22.373+0000] {standard_task_runner.py:60} INFO - Started process 348 to run task
[2025-07-12T14:21:22.376+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'flight_data_etl', 'load_to_database', 'scheduled__2025-07-12T06:00:00+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/flight_data_etl.py', '--cfg-path', '/tmp/tmp9wmlbxl2']
[2025-07-12T14:21:22.377+0000] {standard_task_runner.py:88} INFO - Job 53: Subtask load_to_database
[2025-07-12T14:21:22.399+0000] {task_command.py:423} INFO - Running <TaskInstance: flight_data_etl.load_to_database scheduled__2025-07-12T06:00:00+00:00 [running]> on host b78d8dd28f9c
[2025-07-12T14:21:22.589+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_engineer' AIRFLOW_CTX_DAG_ID='flight_data_etl' AIRFLOW_CTX_TASK_ID='load_to_database' AIRFLOW_CTX_EXECUTION_DATE='2025-07-12T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-12T06:00:00+00:00'
[2025-07-12T14:21:22.598+0000] {base.py:83} INFO - Using connection ID 'postgres_default' for task execution.
[2025-07-12T14:21:22.619+0000] {logging_mixin.py:188} INFO - Loaded 10 airport records
[2025-07-12T14:21:22.624+0000] {base.py:83} INFO - Using connection ID 'postgres_default' for task execution.
[2025-07-12T14:21:22.654+0000] {logging_mixin.py:188} INFO - Loaded 1000 scheduled flight records
[2025-07-12T14:21:22.673+0000] {base.py:83} INFO - Using connection ID 'postgres_default' for task execution.
[2025-07-12T14:21:23.054+0000] {logging_mixin.py:188} INFO - Loaded 11346 real-time flight records
[2025-07-12T14:21:23.055+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-07-12T14:21:23.061+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=flight_data_etl, task_id=load_to_database, execution_date=20250712T060000, start_date=20250712T142122, end_date=20250712T142123
[2025-07-12T14:21:23.103+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-07-12T14:21:23.110+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
