[2025-07-12T15:11:49.834+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flight_ml_dag.prepare_ml_data manual__2025-07-12T15:11:48.823661+00:00 [queued]>
[2025-07-12T15:11:49.837+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flight_ml_dag.prepare_ml_data manual__2025-07-12T15:11:48.823661+00:00 [queued]>
[2025-07-12T15:11:49.837+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-07-12T15:11:49.842+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): prepare_ml_data> on 2025-07-12 15:11:48.823661+00:00
[2025-07-12T15:11:49.845+0000] {standard_task_runner.py:60} INFO - Started process 868 to run task
[2025-07-12T15:11:49.847+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'flight_ml_dag', 'prepare_ml_data', 'manual__2025-07-12T15:11:48.823661+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/flight_ml_dag.py', '--cfg-path', '/tmp/tmpyrbep95x']
[2025-07-12T15:11:49.848+0000] {standard_task_runner.py:88} INFO - Job 76: Subtask prepare_ml_data
[2025-07-12T15:11:49.864+0000] {task_command.py:423} INFO - Running <TaskInstance: flight_ml_dag.prepare_ml_data manual__2025-07-12T15:11:48.823661+00:00 [running]> on host b33104088b45
[2025-07-12T15:11:49.887+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_scientist' AIRFLOW_CTX_DAG_ID='flight_ml_dag' AIRFLOW_CTX_TASK_ID='prepare_ml_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-12T15:11:48.823661+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-12T15:11:48.823661+00:00'
[2025-07-12T15:11:49.890+0000] {base.py:83} INFO - Using connection ID 'postgres_default' for task execution.
[2025-07-12T15:11:49.895+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:221 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-07-12T15:11:49.896+0000] {logging_mixin.py:188} INFO - ‚ùå Error preparing ML data: Execution failed on sql '
        SELECT 
            airline,
            origin_airport,
            destination_airport,
            aircraft_type,
            EXTRACT(HOUR FROM scheduled_departure) as departure_hour,
            EXTRACT(DOW FROM scheduled_departure) as day_of_week,
            flight_duration_minutes,
            status,
            CASE 
                WHEN status IN ('Delayed', 'Cancelled') THEN 1 
                ELSE 0 
            END as is_delayed
        FROM scheduled_flights
        WHERE scheduled_departure IS NOT NULL
        AND flight_duration_minutes IS NOT NULL;
        ': function pg_catalog.date_part(unknown, text) does not exist
LINE 7:             EXTRACT(HOUR FROM scheduled_departure) as depart...
                    ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
[2025-07-12T15:11:49.896+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 2018, in execute
    cur.execute(*args, **kwargs)
psycopg2.errors.UndefinedFunction: function pg_catalog.date_part(unknown, text) does not exist
LINE 7:             EXTRACT(HOUR FROM scheduled_departure) as depart...
                    ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/flight_ml_dag.py", line 59, in prepare_ml_data
    df = postgres_hook.get_pandas_df(ml_query)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 221, in get_pandas_df
    return psql.read_sql(sql, con=conn, params=parameters, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 564, in read_sql
    return pandas_sql.read_query(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 2078, in read_query
    cursor = self.execute(*args)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 2030, in execute
    raise ex from exc
pandas.errors.DatabaseError: Execution failed on sql '
        SELECT 
            airline,
            origin_airport,
            destination_airport,
            aircraft_type,
            EXTRACT(HOUR FROM scheduled_departure) as departure_hour,
            EXTRACT(DOW FROM scheduled_departure) as day_of_week,
            flight_duration_minutes,
            status,
            CASE 
                WHEN status IN ('Delayed', 'Cancelled') THEN 1 
                ELSE 0 
            END as is_delayed
        FROM scheduled_flights
        WHERE scheduled_departure IS NOT NULL
        AND flight_duration_minutes IS NOT NULL;
        ': function pg_catalog.date_part(unknown, text) does not exist
LINE 7:             EXTRACT(HOUR FROM scheduled_departure) as depart...
                    ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

[2025-07-12T15:11:49.900+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=flight_ml_dag, task_id=prepare_ml_data, execution_date=20250712T151148, start_date=20250712T151149, end_date=20250712T151149
[2025-07-12T15:11:49.903+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 76 for task prepare_ml_data (Execution failed on sql '
        SELECT 
            airline,
            origin_airport,
            destination_airport,
            aircraft_type,
            EXTRACT(HOUR FROM scheduled_departure) as departure_hour,
            EXTRACT(DOW FROM scheduled_departure) as day_of_week,
            flight_duration_minutes,
            status,
            CASE 
                WHEN status IN ('Delayed', 'Cancelled') THEN 1 
                ELSE 0 
            END as is_delayed
        FROM scheduled_flights
        WHERE scheduled_departure IS NOT NULL
        AND flight_duration_minutes IS NOT NULL;
        ': function pg_catalog.date_part(unknown, text) does not exist
LINE 7:             EXTRACT(HOUR FROM scheduled_departure) as depart...
                    ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
; 868)
[2025-07-12T15:11:49.950+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-12T15:11:49.962+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
